# Site settings
title: "Hongjun Lee's resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Hongjun Lee"
resume_title:                   "Computer Vision Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hongjun1991@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82-10-2047-6026"
resume_contact_address:         "Room 415, Engineering center annex, 222, Wangsimni-ro, Seongdong-gu, Seoul, Republic of Korea"

resume_header_contact_info:     "Room 415, Engineering center annex, 222, Wangsimni-ro, Seongdong-gu, Seoul, Republic of Korea • +82-10-2047-6026 • hongjun1991@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I received a B.S. degree in electronics and computer engineering from Hanyang Unviersity, Seoul, Korea in 2015, where he is currently pursuing a Ph.D. degree. His research interests include generative adversarial networks, data augmentation, perspective distortion correction, and stereo vision</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      false
resume_section_projects:        true
resume_section_publications:    true
resume_section_recognition:     true
resume_section_skills:          false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/HongjunLee"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "http://www.linkedin.com/in/HJLEE91"
  resume_instagram_url:         "https://www.instagram.com/dlghdwns_/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
